# Generated by Django 3.2.9 on 2022-06-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocao_pet', '0002_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='contato_email',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='localizacao',
            field=models.CharField(help_text='Formato: Cidade-Estado. Ex: Araraquara-SP', max_length=100),
        ),
    ]
